### PR TITLE
Add cflib support for coldbox

### PR DESCRIPTION
**Pull request by richardherbert**
ColdBox supports the [inclusion of cflib udfs via CommandBox](https://commandbox.ortusbooks.com/package-management/code-endpoints/cflib). 

This feature has a dependancy on the existence of the URL https://cflib.org/udfdownload/[udf name].

I assume that the creation of these files was lost in the migration to Jekyll.

This PR restores that feature and files created. The overhead, from a management perspective, is the duplication of simple file in the /udfdownload/ directory to match the name of the udf. From a performance standpoint, the regeneration of the site is about twice as long as double the number of files are generated.

An implementation of this PR can be seen at [https://cflib2017.netlify.com/](https://cflib2017.netlify.com/)

### CODE REVIEW

**Comment by cfjedimaster** [comment]
I'm being lazy, but confirm you added a short note to the News pod on the home page describing this update.

**Comment by richardherbert** [comment]
Sorry - do you want me to add some words?

**Comment by cfjedimaster** [comment]
Yes - literally a one line sentence is fine.

**Comment by richardherbert** [comment]
Note added. Anything more I can do to help, please let me know.

**Comment by cfjedimaster** [comment]
Damn - your code in the layout to get the data is sweet!

**Comment by richardherbert** [comment]
Thanks. It took some thought (Googling)!

**Pull request merged**
